stages:
  - mirror

mirror_repo:
  stage: mirror
  tags:
    - mirror
  script:
    - git config --global user.email "${GLOBAL_USER_EMAIL}"
    - git config --global user.name "${GLOBAL_USER_NAME}"
    # Clone the GitHub repository as a bare repository
    - git clone --mirror https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/${CI_PROJECT_NAME}.git ${CI_PROJECT_NAME}.git
    - cd ${CI_PROJECT_NAME}.git
    # Push all changes to the GitLab repository
    - git push --mirror http://gitlab-ci-token:${GITLAB_PERSONAL_ACCESS_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_PATH}.git
  only:
    - schedules
